# Generated by Django 3.2.5 on 2022-07-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descr', models.CharField(max_length=200)),
                ('RA', models.FloatField()),
                ('DEC', models.FloatField()),
                ('size', models.CharField(max_length=10)),
                ('Mv', models.CharField(max_length=10)),
                ('objtype', models.CharField(max_length=10)),
                ('distance', models.FloatField()),
                ('rating', models.IntegerField()),
                ('dark', models.BooleanField()),
                ('finder', models.ImageField(default='default.gif', upload_to='finders')),
                ('comments', models.TextField(max_length=1000)),
            ],
        ),
    ]
