"""
Django settings for obstool project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

# Find Bokeh
import bokeh
from astropy.utils.iers import conf as iers_conf
iers_conf.auto_download = False

BOKEH_JS = os.path.join(os.path.dirname(bokeh.__file__),'server','static','js')
BOKEH_CSS = os.path.join(os.path.dirname(bokeh.__file__),'server','static','css')
# Here are some site-wide configuration settings that can be changed 
# on a per-user basis:
# The 3-D position of the observing site
OBSERVING_LONG = "-118.0590"
OBSERVING_LAT = "34.2170"
OBSERVING_ELEV = 1579

# The effective horizon for the observing site.  For now, this is just a
# constant altitude, but later maybe user can specify a real horizon
# as alt/az points?
ALT_LIMIT = 32.0
# This is a soft limit that maybe the user should be worried
ALT_SOFT_LIMIT = 40.0
# An hour-angle limit
HA_LIMIT = 4.0
# This is a soft limit that maybe the user should be worried
HA_SOFT_LIMIT = 3.0
# Declination limit
DEC_LIMIT = -27.0

# eyepieces and field-of-views
fovs = {
        '50mm':6,
        '80mm':9,
        '100mm':11,
        }

FINDER_BASE_SIZE=60      # arc-min
FINDER_SIZE=10      # arc-min
FINDER_FLIP=None # default finder is North up, East left.  Specify
                   # "leftright", "topbottom", or "both" to change this
FINDER_ORIENTATION="North up, East left"     # let's be clear about this
FINDER_REVERSE=None     # reverse palette.  Set to None, to have dark sky
FINDER_LOW=0     # stretch low
FINDER_HIGH=255     # stretch high
TZ_OFFSET=0        # offset (in hours) from UTC you want to use

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(f$(q#nm$h1qb+de=a__*@z^bl**f(#4bq#mh**q0(&z__j8+x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
SITE_ROOT = os.path.join(BASE_DIR, 'static')


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'navigator',
)

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'obstool.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'mytemplates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'obstool.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'objects': {
        'ENGINE': 'django.db.backends.sqlite3', # Add 'postgresql_psycopg2', 'postgresql', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': os.path.join(BASE_DIR,'objects.sql'),
    }
}
DATABASE_ROUTERS = ['obstool.router.MyAppRouter']


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = '/static/'
